// Generated by CoffeeScript 2.7.0
(function() {
  var CACHE_KEY, FETCH_TIMEOUT_MS, TARGET, cached, container, escapeHtml, fetchWithTimeout, getLanguages, loadProjects, parseLanguages, projectCard, projectsContainer, readCache, ref, renderProjects, sameLanguages, showProjectsError, startedAt, typewriter, writeCache;

  TARGET = 'languages.svg';

  // El SVG local fue generado desde github-stats-extended (camo.githubusercontent.com)
  // y se lee same-origin, sin problemas de CORS. Se extraen los nombres de los
  // textos con data-testid="lang-name" (formato: "HTML 45.03%").

  FETCH_TIMEOUT_MS = 15000;

  CACHE_KEY = 'livrasand.languages';
  PROJECTS_CACHE_KEY = 'livrasand.projects';

  fetchWithTimeout = async function(url) {
    var controller, response, timer;
    controller = new AbortController();
    timer = setTimeout((function() {
      return controller.abort();
    }), FETCH_TIMEOUT_MS);
    try {
      response = (await fetch(url, {
        signal: controller.signal
      }));
    } finally {
      clearTimeout(timer);
    }
    return response;
  };

  // Extrae los lenguajes del SVG local (etiquetas data-testid="lang-name").
  // Cada texto viene en formato "HTML 45.03%"; se descarta el porcentaje.
  parseLanguages = function(svgText) {
    var doc, i, lang, len, name, names, nodes, parser;
    if (typeof svgText !== 'string' || svgText.includes('lang-name') === false) {
      return [];
    }
    parser = new DOMParser();
    doc = parser.parseFromString(svgText, 'image/svg+xml');
    nodes = doc.querySelectorAll('[data-testid="lang-name"]');
    names = [];
    for (i = 0, len = nodes.length; i < len; i++) {
      lang = nodes[i].textContent || '';
      name = lang.replace(/\d+(\.\d+)?%$/, '').trim();
      if (name) {
        names.push(name);
      }
    }
    return names;
  };

  getLanguages = async function() {
    var err, error1, languages, response;
    try {
      response = (await fetchWithTimeout(TARGET));
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }
      languages = parseLanguages((await response.text()));
      if (languages.length) {
        return languages;
      }
      console.error('No programming languages found in the languages.svg.');
    } catch (error1) {
      err = error1;
      console.error('Could not load programming languages:');
      console.error(err);
      console.error(err != null ? err.message : void 0);
    }
    return [];
  };

  readCache = function() {
    var error;
    try {
      return JSON.parse(localStorage.getItem(CACHE_KEY));
    } catch (error1) {
      error = error1;
      return null;
    }
  };

  writeCache = function(languages) {
    var error;
    try {
      return localStorage.setItem(CACHE_KEY, JSON.stringify({
        languages: languages,
        fetchedAt: Date.now()
      }));
    } catch (error1) {
      error = error1;
    }
  };

  readProjectsCache = function() {
    var error;
    try {
      return JSON.parse(localStorage.getItem(PROJECTS_CACHE_KEY));
    } catch (error1) {
      error = error1;
      return null;
    }
  };

  writeProjectsCache = function(repos) {
    var error;
    try {
      return localStorage.setItem(PROJECTS_CACHE_KEY, JSON.stringify({
        repos: repos,
        fetchedAt: Date.now()
      }));
    } catch (error1) {
      error = error1;
    }
  };

  sameRepos = function(a, b) {
    if (a.length !== b.length) return false;
    return a.every(function(repo, index) {
      return repo.id === b[index].id && repo.updated_at === b[index].updated_at;
    });
  };

  // Sin almacenamiento disponible, se sigue sin cache
  sameLanguages = function(a, b) {
    return a.length === b.length && a.every(function(language, index) {
      return language === b[index];
    });
  };

  escapeHtml = function(text) {
    var div;
    div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  };

  typewriter = function(container, languages, loadTimeMs) {
    var sentence, speed, texts, write;
    if (!container) {
      return;
    }
    texts = languages.length === 0 ? ['unknown'] : languages;
    sentence = texts.map(function(language, index) {
      var comma;
      comma = index < texts.length - 1 ? ',' : '';
      return `\"${language}\"${comma}`;
    }).join(' ');
    container.textContent = '';
    // A mayor tiempo de carga, más rápido se escribe el texto
    speed = Math.max(12, Math.min(55, loadTimeMs / 80));
    write = function(position) {
      var char, delay, typed;
      typed = escapeHtml(sentence.slice(0, position));
      container.innerHTML = typed + '<span class="caret"></span>';
      if (position >= sentence.length) {
        return;
      }
      // Ritmo de programador: latencia base con pequeños titubeos
      delay = speed * (0.5 + Math.random());
      char = sentence[position];
      // Pausas naturales tras comas y comillas
      if (char === ',') {
        delay += 220;
      } else if (char === '"' && Math.random() < 0.5) {
        delay += 80;
      }
      return setTimeout((function() {
        return write(position + 1);
      }), delay);
    };
    return write(0);
  };

  loadProjects = async function() {
    var cached, err, error1, items, response, url;
    projectsContainer = document.querySelector('#projects-list');
    if (!projectsContainer) {
      return;
    }
    cached = readProjectsCache();
    if (cached != null ? cached.repos : void 0) {
      renderProjects(cached.repos);
    }
    url = 'https://api.github.com/users/livrasand/repos?sort=updated&per_page=100&type=owner';
    try {
      response = (await fetchWithTimeout(url));
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }
      items = await response.json();
      if (cached != null ? cached.repos : void 0) {
        if (!sameRepos(items, cached.repos)) {
          writeProjectsCache(items);
          console.log('Projects cache updated.');
          renderProjects(items);
        } else {
          writeProjectsCache(items);
        }
      } else {
        writeProjectsCache(items);
        renderProjects(items);
      }
    } catch (error1) {
      err = error1;
      console.error('Could not load projects:');
      console.error(err);
      if (!(cached != null ? cached.repos : void 0)) {
        return showProjectsError();
      }
    }
  };

  renderProjects = function(repos) {
    var i, len, repo, results;
    repos = repos.filter(function(item) {
      return !item.fork;
    });
    if (repos.length === 0) {
      showProjectsError();
      return;
    }
    projectsContainer.textContent = '';
    results = [];
    for (i = 0, len = repos.length; i < len; i++) {
      repo = repos[i];
      results.push(projectsContainer.appendChild(projectCard(repo)));
    }
    return results;
  };

   projectCard = function(repo) {
     var card, line, name, path, prop, url;
     card = document.createElement('span');
     card.className = 'project';
     line = document.createElement('span');
     line.className = 'project-line';
     prop = document.createElement('span');
     prop.className = 'prop';
     prop.style.paddingLeft = '15px';
     prop.textContent = 'name:';
     name = document.createElement('a');
     name.className = 'project-name';
     name.href = repo.html_url;
     name.target = '_blank';
     name.rel = 'noopener noreferrer';
     name.textContent = `\"${repo.name}\",`;
     line.appendChild(prop);
     line.appendChild(name);
     card.appendChild(line);
     line = document.createElement('span');
     line.className = 'project-line';
     prop = document.createElement('span');
     prop.className = 'prop';
     prop.style.paddingLeft = '15px';
     prop.textContent = 'url:';
     url = document.createElement('a');
     url.className = 'project-path';
     url.href = repo.html_url;
     url.target = '_blank';
     url.rel = 'noopener noreferrer';
     url.textContent = `\"${repo.full_name || repo.html_url}\",`;
     line.appendChild(prop);
     line.appendChild(url);
     card.appendChild(line);
     return card;
   };

  showProjectsError = function() {
    return projectsContainer.textContent = '(no se pudieron cargar los proyectos)';
  };

  container = document.querySelector('#languages');

  setupDropdown = function() {
    var dropdown, menu, toggle;
    toggle = document.querySelector('.dropdown-toggle');
    if (!toggle) {
      return;
    }
    dropdown = toggle.closest('.dropdown');
    menu = dropdown.querySelector('.dropdown-menu');
    toggle.addEventListener('click', function(event) {
      event.stopPropagation();
      return dropdown.classList.toggle('open');
    });
    document.addEventListener('click', function(event) {
      if (dropdown.classList.contains('open') && !dropdown.contains(event.target)) {
        return dropdown.classList.remove('open');
      }
    });
    return menu.addEventListener('click', function(event) {
      var option, page;
      option = event.target.closest('.dropdown-option[data-target]');
      if (option) {
        page = option.dataset.target === 'main' ? 'index.html' : `${option.dataset.target}.html`;
        return window.location.assign(page);
      }
      if (!event.target.closest('#toggle-theme')) {
        return dropdown.classList.remove('open');
      }
    });
  };

  setupThemeToggle = function() {
    var applyTheme, button, scheme, THEME_KEY;
    THEME_KEY = 'livrasand-theme';
    button = document.querySelector('#toggle-theme');
    if (!button) {
      return;
    }
    scheme = localStorage.getItem(THEME_KEY);
    if (scheme !== 'dark' && scheme !== 'light') {
      scheme = matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
    }
    applyTheme = function() {
      document.documentElement.dataset.theme = scheme;
      return button.textContent = `theme: ${scheme}`;
    };
    button.addEventListener('click', function() {
      scheme = scheme === 'light' ? 'dark' : 'light';
      localStorage.setItem(THEME_KEY, scheme);
      return applyTheme();
    });
    return applyTheme();
  };

  setupDropdown();

  setupThemeToggle();

  if (container) {
    cached = (ref = readCache()) != null ? ref.languages : void 0;
    if (cached != null ? cached.length : void 0) {
      // Respuesta instantánea desde el cache
      console.log('Languages from cache:');
      console.log('Languages:', cached);
      typewriter(container, cached, 0);
      // Revisa en segundo plano si el cache tiene una versión más nueva
      getLanguages().then(function(languages) {
        if (languages.length === 0) {
          return;
        }
        if (!sameLanguages(languages, cached)) {
          writeCache(languages);
          console.log('Languages cache updated:');
          console.log('Languages:', languages);
          return typewriter(container, languages, 0);
        } else {
          // Mismo contenido: solo se refresca la fecha de captura
          return writeCache(languages);
        }
      });
    } else {
      // Sin cache: descarga, guarda y se muestra
      startedAt = performance.now();
      getLanguages().then(function(languages) {
        var loadTimeMs;
        loadTimeMs = performance.now() - startedAt;
        console.log(`Languages loaded in ${loadTimeMs.toFixed(0)} ms:`);
        console.log('Languages:', languages);
        writeCache(languages);
        return typewriter(container, languages, loadTimeMs);
      });
    }
  }

  loadProjects();

}).call(this);
